ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # Import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include("main.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Hero(models.Model):
    subtitle = models.CharField(max_length=255,null=True, blank=True)
    tile = models.CharField(max_length=255,null=True, blank=True)
    description = models.CharField(max_length=255,null=True, blank=True)
    price = models.CharField(max_length=255,null=True, blank=True)
    image = models.ImageField(upload_to='hero/')


class Coupon(models.Model):
    value = models.CharField(max_length=200)
    reduction = models.DecimalField(max_digits=5, decimal_places=2)

class Total(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    #reduction = models.DecimalField(max_digits=10)

class Panier(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    produits = models.ManyToManyField('Produit', through='ItemPanier')



class ItemPanier(models.Model):
    panier = models.ForeignKey(Panier, on_delete=models.CASCADE)
    produit = models.ForeignKey('Produit', on_delete=models.CASCADE)
    quantite = models.PositiveIntegerField(default=1)

    @property
    def total_cost(self):
        return self.quantite * self.produit.prix


class Produit(models.Model):
    nom = models.CharField(max_length=200)
    image = models.ImageField(upload_to='produits/')
    prix = models.DecimalField(max_digits=10, decimal_places=2)
    reduction = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    categorie = models.CharField(max_length=100)
    etat = models.CharField(max_length=100)
    description = models.TextField(null=True)

    def __str__(self):
        return self.nom


class Adresse(models.Model):
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='adresse/')
    iban = models.CharField(max_length=34, default='')  # Valeur par défaut vide pour IBAN
    code_banque = models.CharField(max_length=20, default='')  # Valeur par défaut vide pour le code de la banque
    numero_de_compte = models.CharField(max_length=30, default='')  # Valeur par défaut vide pour le numéro de compte
    bic = models.CharField(max_length=11, default='')  # Valeur par défaut vide pour BIC
    titulaire = models.CharField(max_length=200, default='')  # Valeur par défaut vide pour le titulaire
    pays = models.CharField(max_length=100, default='')  # Valeur par défaut vide pour le pays

    def __str__(self):
        return self.titulaire


class UserData(models.Model):
    prenoms = models.CharField(max_length=255)
    nom_de_famille = models.CharField(max_length=255)
    email = models.EmailField()
    telephone = models.CharField(max_length=20)
    ville = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    code_postal = models.CharField(max_length=5)


class Receipt(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    receipt_image = models.ImageField(upload_to='receipts/')
    upload_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Receipt for {self.user.username} uploaded on {self.upload_date}"

templates/all_product.html
{% extends "base.html" %}

{% block content %}

<!-- Start Trending Product Area -->
<section class="trending-product section" style="margin-top: 12px;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <h2>Boutique</h2>
                </div>
            </div>
        </div>
        <div class="row">
            {% for produit in produits %}
            <div class="col-lg-3 col-md-6 col-6">
                <div class="single-product">
                    <div class="product-image">
                        <a href="{% url "detail" produit.id %}">
                        <img src="{{produit.image.url}}" alt="#">
                        </a>
                    </div>
                    <div class="product-info">
                        <h4 class="title">
                            <a href="{% url "detail" produit.id %}">{{produit.nom}}</a>
                        </h4>
                        <ul class="review">
                            <li><i class="lni lni-star-filled"></i></li>
                            <li><i class="lni lni-star-filled"></i></li>
                            <li><i class="lni lni-star-filled"></i></li>
                            <li><i class="lni lni-star-filled"></i></li>
                        </ul>
                        <div class="price">
                            <span>{{produit.prix}} €</span>
                        </div>
                        <div class="button">
                            <a href="{% url 'ajouter_au_panier' produit.id %}" class="btn"><i class="lni lni-cart"></i> Add </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}   
        </div>
    </div>
</section>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>ShopGrids - Boutique de vélo, cross, skateboard, moto.</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href="assets/images/favicon.svg" />

    <!-- ========================= CSS here ========================= -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css"%}" />
    <link rel="stylesheet" href="{% static "css/LineIcons.3.0.css"%}" />
    <link rel="stylesheet" href="{% static "css/tiny-slider.css"%}" />
    <link rel="stylesheet" href="{% static "css/glightbox.min.css"%}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static "css/main.css"%}" />""

</head>

<body>
    <!--[if lte IE 9]>
      <p class="browserupgrade">
        You are using an <strong>outdated</strong> browser. Please
        <a href="https://browsehappy.com/">upgrade your browser</a> to improve
        your experience and security.
      </p>
    <![endif]-->

    <!-- Preloader -->

    <!-- /End Preloader -->

    <!-- Start Header Area -->
    <header class="header navbar-area fixed-top">
        <!-- Start Header Middle -->
        <div class="header-middle  fixed-top" style="background-color:white;">
            <div class="container ">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-md-3 col-7">
                        <!-- Start Header Logo -->
                        <a class="navbar-brand" href="{% url "index" %}">
                            <img src="{% static "images/logo/logo.svg"%}" alt="Logo">
                        </a>
                        <!-- End Header Logo -->
                    </div>
                    <div class="col-lg-5 col-md-7 d-xs-none">
                        <!-- Start Main Menu Search -->
                        <div class="main-menu-search">
                            <!-- navbar search start -->
                            <div class="navbar-search search-style-5">
                                <div class="search-input">
                                    <input type="text" placeholder="Search">
                                </div>
                                <div class="search-btn">
                                    <button><i class="lni lni-search-alt"></i></button>
                                </div>
                            </div>
                            <!-- navbar search Ends -->
                        </div>
                        <!-- End Main Menu Search -->
                    </div>
                    <div class="col-lg-4 col-md-2 col-5">
                        <div class="middle-right-area">
                            <div class="navbar-cart">


                                
                              
                                <div class="wishlist">
                                    <a href="{% url "index" %}">
                                        <i class="lni lni-home"></i>
                                    </a>
                                </div>
                                <div class="wishlist">
                                    <a href="{% url "shop" %}">
                                        <i class="fas fa-store"></i>
                                    </a>
                                </div>
                        
                                <div class="cart-items">
                                    <a href="javascript:void(0)" class="main-btn">
                                        <i class="lni lni-cart"></i>
                                        <span class="total-items"> {% if totalitem %}{{totalitem}} {% else %} 0{% endif %}</span>
                                    </a>
                                    <!-- Shopping Item -->
                                    <div class="shopping-item">
                                        <div class="dropdown-cart-header">
                                            <span>{{totalitem}} Produits</span>
                                            <a href="{% url "cart" %}">Voir</a>
                                        </div>
                                        <ul class="shopping-list">
                                            {% for item in items %}
                                            <li>
                                                <a href="{% url 'supprimer_du_panier' item.id %}" class="remove" title="Remove this item"><i
                                                        class="lni lni-close"></i></a>
                                                <div class="cart-img-head">
                                                    <a class="cart-img" href="product-details.html"><img
                                                            src="{{item.produit.image.url}}" alt="#"></a>
                                                </div>

                                                <div class="content">
                                                    <h4><a href="product-details.html">
                                                            {{item.produit.nom}}</a></h4>
                                                    <p class="quantity">{{item.quantite}}x - <span class="amount">{{item.produit.prix}} €</span></p>
                                                </div>
                                            </li>
                                            {% endfor %}
                                        </ul>
                                        <div class="bottom">
                                            <div class="total">
                                                <span>Total</span>
                                                <span class="total-amount">{{total}} €</span>
                                            </div>
                                            <div class="button">
                                                <a href="{% url "checkout" %}" class="btn animate">Paiement</a>
                                            </div>
                                        </div>
                                    </div>
                                    <!--/ End Shopping Item -->
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>

 

            </div>
        </div>
        <!-- End Header Middle -->
        
    </header>


    
    <!-- End Header Area -->




   {% block content %}{% endblock content %}

    <!-- Start Footer Area -->
    <footer class="footer">
        <!-- Start Footer Top -->
        <div class="footer-top">
            <div class="container">
                <div class="inner-content">
                    <div class="row">
                        <div class="col-lg-3 col-md-4 col-12">
                            <div class="footer-logo">
                                <a href="index.html">
                                    <img src="{% static "images/logo/white-logo.svg"%}" alt="#">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Footer Top -->
        <!-- Start Footer Middle -->
        <div class="footer-middle">
            <div class="container">
                <div class="bottom-inner">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 col-12">
                            <!-- Single Widget -->
                            <div class="single-footer f-contact">
                                <h3>Vous pouvez nous contacter</h3>
                                <p class="phone">Phone: +1 (900) 33 169 7720</p>
                                <ul>
                                    <li><span>Lundi-Vendredi: </span> 9.00 - 20.00 </li>
                                    <li><span>Samedi: </span> 10.00  - 18.00 </li>
                                </ul>
                                <p class="mail">
                                    <a href="mailto:support@shopgrids.com">support@shopgrids.com</a>
                                </p>
                            </div>
                            <!-- End Single Widget -->
                        </div>
                        
                        
                        
                    </div>
                </div>
            </div>
        </div>
        <!-- End Footer Middle -->
        <!-- Start Footer Bottom -->
        <div class="footer-bottom">
            <div class="container">
                <div class="inner-content">
                    <div class="row align-items-center">
                        <div class="col-lg-4 col-12">
                            <div class="payment-gateway">
                                <span>Nous acceptons :</span>
                                <img src="{% static "images/footer/credit-cards-footer.png"%}" alt="#">
                            </div>
                        </div>
                        <div class="col-lg-4 col-12">
                            <div class="copyright">
                                <p>Designed and Developed by topshop</p>
                            </div>
                        </div>
                        <div class="col-lg-4 col-12">
                            <ul class="socila">
                                <li>
                                    <span>Suivez nous sur :</span>
                                </li>
                                <li><a href="javascript:void(0)"><i class="lni lni-facebook-filled"></i></a></li>
                                <li><a href="javascript:void(0)"><i class="lni lni-twitter-original"></i></a></li>
                                <li><a href="javascript:void(0)"><i class="lni lni-instagram"></i></a></li>
                                <li><a href="javascript:void(0)"><i class="lni lni-google"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Footer Bottom -->
    </footer>
    <!--/ End Footer Area -->

    <!-- ========================= scroll-top ========================= -->
    <a href="#" class="scroll-top">
        <i class="lni lni-chevron-up"></i>
    </a>

    <!-- ========================= JS here ========================= -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/tiny-slider.js"%}"></script>
    <script src="{% static "js/glightbox.min.js"%}"></script>
    <script src="{% static "js/main.js"%}"></script>
    <!-- Import jQuery library -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- Import Bootstrap JavaScript (if using Bootstrap) -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>

<!-- Your existing HTML code -->



    <script type="text/javascript">
      
        //========= Hero Slider 
        tns({
            container: '.hero-slider',
            slideBy: 'page',
            autoplay: true,
            autoplayButtonOutput: false,
            mouseDrag: true,
            gutter: 0,
            items: 1,
            nav: false,
            controls: true,
            controlsText: ['<i class="lni lni-chevron-left"></i>', '<i class="lni lni-chevron-right"></i>'],
        });

        //======== Brand Slider
        tns({
            container: '.brands-logo-carousel',
            autoplay: true,
            autoplayButtonOutput: false,
            mouseDrag: true,
            gutter: 15,
            nav: false,
            controls: false,
            responsive: {
                0: {
                    items: 1,
                },
                540: {
                    items: 3,
                },
                768: {
                    items: 5,
                },
                992: {
                    items: 6,
                }
            }
        });
    </script>
</body>

</html>

templates/cart_summary.html
{% extends 'base.html' %}

{% block content %}

<div class="card" style="margin-top:55px">
    <div class="card-body">
      <h5 class="card-title">Panier</h5>

      <!-- Default Table -->
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Produits</th>
            <th scope="col">Nom</th>
            <th scope="col">Prix</th>
            <th scope="col">Total</th>
          </tr>
        </thead>
        <tbody>
            {% for item in items %}
          <tr>
            <th scope="row"><img src='{{item.produit.image.url}}' alt="{{item.produit.nom}}" style="width:50px"></th>
            <td>{{item.produit.nom}}</td>
            <td>{{item.quantite}} x {{item.produit.prix}} €</td>
            <td>{{item.total_cost}} €</td>
          </tr>
          {%endfor%}
        </tbody>
      </table>
      <!-- End Default Table Example -->
    </div>
  </div>




<div class="card text-left">
  <div class="card-body">

    <div class="col-12">
        <div class="form-floating mb-3">
            <input name="Coupon" id="coupon" class="form-control"  placeholder="Entrez un code coupon (si vous en avez)">
            <label for="coupon">Entrez un code coupon (si vous en avez)</label>
          </div>
    </div>

        <table class="table">
            <thead>
              <tr>
                <th scope="col">total</th>
                <th scope="col">Livraison</th>
                <th scope="col">économisez</th>
                <th scope="col">payez</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">{{ total  }} €</th>
                <td>Gratuit</td>
                <td>40.00 €</td>
                <td>{{total}} €</td>
              </tr>
            </tbody>
        </table>
        
        <a href="{% url 'checkout'  %}" class="btn btn-outline-primary" id="checkout">Paiement</a>
        <a href="{% url 'shop'%}" class="btn btn-outline-primary">Continuer à acheter</a>

  </div>
</div>


  

{% endblock content %}

templates/checkout.html
{% extends "base.html" %}

{% block content %}

<div class="card" style="margin-top:70px;">
    <div class="card-body">
      <h5 class="card-title">Renseignez vos information pour la livraison</h5>

      <!-- Multi Columns Form -->
      <form class="row g-3" method="post" action="{% url 'adresse' %}">
        <div class="col-md-12">
          <label for="inputName5" class="form-label" style="color:black;">Nom </label>
          <input type="text" class="form-control" id="inputName5" name="name" placeholder="" required>
        </div>
        <div class="col-md-12">
            <label for="inputName5" class="form-label" style="color:black;">Prénoms</label>
            <input type="text" class="form-control" id="inputName5" name="firstname" placeholder="" required>
          </div>
        <div class="col-md-6">
          <label for="inputEmail5" class="form-label" style="color:black;">Email</label>
          <input type="email" class="form-control" id="inputEmail5" name="email" placeholder="" required>
        </div>
        <div class="col-md-6">
          <label for="inputPassword5" class="form-label" style="color:black;">Téléphone</label>
          <input type="number" class="form-control" id="inputPassword5" name="number" placeholder="" required>
        </div>
        <div class="col-12">
          <label for="inputAddress5" class="form-label" style="color:black;">Address</label>
          <input type="text" class="form-control" id="inputAddres5s" placeholder="1234 Main St" name="address" required>
        </div>
        <div class="col-12">
          <label for="inputAddress2" class="form-label" style="color:black;">Address 2</label>
          <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor / facultatif">
        </div>
        <div class="col-md-6">
          <label for="inputCity" class="form-label" style="color:black;">Ville</label>
          <input type="text" class="form-control" id="inputCity" name="state-province" placeholder="" required>
        </div>
    
        <div class="col-md-2">
          <label for="inputZip" class="form-label" style="color:black;">code postal</label>
          <input type="text" class="form-control" id="inputZip" name="post" placeholder="" required>
        </div>
        <div class="col-12">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" id="gridCheck">
            <label class="form-check-label" for="gridCheck">
              Check me out
            </label>
          </div>
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-primary">Proceder au paiement</button>
          <button type="reset" class="btn btn-secondary">Réinitialiser</button>
        </div>
      </form><!-- End Multi Columns Form -->

    </div>
  </div>

</div>

{% endblock content %}

templates/index.html
{% extends "base.html" %}

 {% load static %}

{% block content %}

<!-- Start Hero Area -->
<section class="hero-area" style="margin-top:40px;">
    <div class="container">
        <div class="row">


            <div class="col-lg-8 col-12 custom-padding-right">
                <div class="slider-head">
                    <!-- Start Hero Slider -->
                    <div class="hero-slider">
                        <!-- Start Single Slider -->
                        {% for hero in heros %}
                        <div class="single-slider"
                            style="background-image: url({{hero.image.url}});">
                            <div class="content">
                                <h2><span>{{hero.subtitle}}</span>
                                    {{hero.tile}}
                                </h2>
                                <p>{{hero.description}}</p>
                                <h3><span>Seulement</span> {{hero.price}} €</h3>
                                <div class="button">
                                    <a href="{% url "shop" %}" class="btn">Achetez maintenant</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- End Hero Slider -->
                </div>
            </div>




            <div class="col-lg-4 col-12">
                <div class="row">
                    <div class="col-lg-12 col-md-6 col-12">
                        <!-- Start Small Banner -->
                        <div class="hero-small-banner style2">
                            <div class="content">
                                <h2>Vente flash !</h2>
                                <p>Économiser jusqu'à 40% sur tout vos achats en ligne ce mois.</p>
                                <div class="button">
                                    <a class="btn" href="{% url "shop" %}">Tout les articles</a>
                                </div>
                            </div>
                        </div>
                        <!-- Start Small Banner -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Hero Area -->




<!-- Start Trending Product Area -->
<section class="trending-product section" style="margin-top: 12px;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <h2>Produits populaire</h2>
                    <p>Nous avons des vélo, moto, cross, buggy, skateboard neuf comme d'occasion.</p>
                </div>
            </div>
        </div>
        <div class="row">
            {% for produit in produits %}
            <div class="col-lg-3 col-md-6 col-6">
                <div class="single-product">
                    <div class="product-image">
                        <a href="{% url "detail" produit.id %}">
                        <img src="{{produit.image.url}}" alt="#">
                        </a>
                    </div>
                    <div class="product-info">
                        <h4 class="title">
                            <a href="{% url "detail" produit.id %}">{{produit.nom}}</a>
                        </h4>
                        <ul class="review">
                            <li><i class="lni lni-star-filled"></i></li>
                            <li><i class="lni lni-star-filled"></i></li>
                            <li><i class="lni lni-star-filled"></i></li>
                            <li><i class="lni lni-star-filled"></i></li>
                        </ul>
                        <div class="price">
                            <span>{{produit.prix}} €</span>
                        </div>
                        <div class="button">
                            <a href="{% url 'ajouter_au_panier' produit.id %}" class="btn"><i class="lni lni-cart"></i> Add </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}    
        </div>
    </div>
</section>



<!-- Start Shipping Info -->
<section class="shipping-info">
    <div class="container">
        <ul>
            <!-- Free Shipping -->
            <li>
                <div class="media-icon">
                    <i class="lni lni-delivery"></i>
                </div>
                <div class="media-body">
                    <h5>Livraison gratuit</h5>
                    <span>À partir de 300€ d'achat</span>
                </div>
            </li>
            <!-- Money Return -->
            <li>
                <div class="media-icon">
                    <i class="lni lni-support"></i>
                </div>
                <div class="media-body">
                    <h5>Support 24/7.</h5>
                    <span>Chat direct ou appel.</span>
                </div>
            </li>
            <!-- Support 24/7 -->
            <li>
                <div class="media-icon">
                    <i class="lni lni-credit-cards"></i>
                </div>
                <div class="media-body">
                    <h5>Paiement en ligne.</h5>
                    <span>Services de paiement sécurisé.</span>
                </div>
            </li>
            <!-- Safe Payment -->
            <li>
                <div class="media-icon">
                    <i class="lni lni-reload"></i>
                </div>
                <div class="media-body">
                    <h5>Retour facile</h5>
                    <span>Pendant 7 jours apres l'achat</span>
                </div>
            </li>
        </ul>
    </div>
</section>
<!-- End Shipping Info -->

{% endblock content %}

templates/payement.html
{% extends "base.html" %}


{% block content %}

<div class="card" style="margin-top:70px;">
    <div class="card-body">
        <h5 class="card-title">Paiement</h5>
            <p class="card-text" style="color:black;">{{addresse.description}}</p>
        <div class="info">
            <h5>Code banque</h5>
            <p>{{ addresse.code_banque }} </p>
        
        
        </div>
        
        <div class="info">
            <h5 style="margin-bottom: 10px;display:block;">Numero de compte</h5>
            <p style="color:black;">{{ addresse.numero_de_compte }} </p>
        </div>
        
        <div class="info">
            <h5>IBAN</h5>
            <p style="color:black;">{{ addresse.iban }} </p>
        </div>
        
        <div class="info">
            <h5>BIC</h5>
            <p style="color:black;">{{ addresse.bic }} </p>
        </div>
        
        <div class="info">
            <h5 style="color:black;">Pays</h5>
            <p>{{ addresse.pays }} </p>
        </div>
        
        <div class="info">
            <h5>Titulaire</h5>
            <p style="color:black;">{{ addresse.titulaire }} </p>
        </div>
    </div>
    
  </div>


  <div class="card text-left" style="margin-bottom:100px;">
    <div class="card-body">
      <h4 class="card-title">Téléverser une preuve de paiement</h4>
      <form method="post" enctype="multipart/form-data" action="{% url 'upload_receipt' %}">
        {% csrf_token %}
        <div class="col-sm-10">
            <input class="form-control" type="file" id="id_receipt_image" name="receipt_image" >
        </div>

        <div class="d-grid gap-2 mt-3">
            <button class="btn btn-primary" type="button">Envoyer</button>
          </div>
    </form>
    </div>
  </div>


{% endblock content %}